apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    kind: Ingress
    name: silly-demo
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: silly-demo.uat.127.0.0.1.nip.io
